<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Plugini</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MoonSharp" Version="3.0.0-beta.1" />
    </ItemGroup>

</Project>
